*** Variables ***
# Checkout Page Locators
${CHECKOUT_TITLE}           xpath://span[@class='title'][text()='Checkout: Your Information']
${FIRST_NAME_FIELD}         id:first-name
${LAST_NAME_FIELD}          id:last-name
${POSTAL_CODE_FIELD}        id:postal-code
${CONTINUE_BUTTON}          id:continue
${FINISH_BUTTON}            id:finish
${COMPLETE_HEADER}          xpath://h2[@class='complete-header']
${BACK_HOME_BUTTON}         id:back-to-products